name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*'           # v로 시작하는 태그 예: v1.7.0
    # (선택) 또는 별표 태그 모두 허용:
    # tags:
    #   - '*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to private registry
        uses: docker/login-action@v2
        with:
          registry: registry.somdle.synology.me

      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # 태그 형식: registry 주소 + 리포지토리 이름 + 태그
          tags: |
            registry.somdle.synology.me/api-main:${{ github.ref_name }}
            registry.somdle.synology.me/api-main:latest
          # 캐시 사용 (선택적)
          cache-from: type=registry,ref=registry.somdle.synology.me/api-main:buildcache
          cache-to: type=registry,ref=registry.somdle.synology.me/api-main:buildcache,mode=max
